### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Litefallen** [Litefallen/spotify_library_edit#1]
TODO

- [x] selecting playlist or fav tracks l
- [x] removing tracks from the playlist
- [x] removing multiple tracks
- [ ] add errorchecks
- [ ] add song/artist search in selected playlist
- [ ]  clean code
- [ ] add music download function?
- [ ] something else
